

Text /* IDEAL_VARIABLE_NAME */;

/* IDEAL_SUB_VARIABLE_SEPARATION */

var /* IDEAL_VARIABLE_NAME */Text = "/* IDEAL_TEXT */";

/* IDEAL_SUB_VARIABLE_SEPARATION */

/* IDEAL_INITIALISATION_START */
/* IDEAL_VARIABLE_NAME */ = new Text(/* IDEAL_VARIABLE_NAME */Text,
style: TextStyle(
fontWeight: FontWeight.bold,
fontSize: 22
),
);
/* IDEAL_INITIALISATION_END */
