directories:
  output: release
  buildResources: assets
  app: src
productName: ElectronReact
appId: org.erb.ElectronReact
files:
  - filter:
      - dist/
      - node_modules/
      - index.html
      - main.prod.js
      - main.prod.js.map
      - package.json
afterSign: .erb/scripts/Notarize.js
mac:
  target:
    - dmg
  type: distribution
  hardenedRuntime: true
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  gatekeeperAssess: false
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
linux:
  target:
    - AppImage
  category: Development
extraResources:
  - filter:
      - ./assets/**
publish:
  provider: github
  owner: electron-react-boilerplate
  repo: electron-react-boilerplate
electronVersion: 11.0.1
